# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:17.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: cm_data
      POSTGRES_PASSWORD: cm_data
    ports:
      - '5433:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./csv:/csv
      - ./all_coin_data:/all_coin_data
      - ./sql:/sql

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  db:
    driver: local
